In [1]:
import pickle
import numpy as np
from sklearn.model_selection import train_test_split
import os
import pandas as pd
path_dataset =  "/blue/bianjiang/fanz/Graph_Dataset/ADRD/whole_dataset_20241107/nebor_50/output_node_features.pickle"
file_dataset = open(path_dataset, 'rb')
df_features = pickle.load(file_dataset)

In [2]:
df_features = df_features[['PATID', 'next_status']]
print(df_features['next_status'].value_counts())
df_features.index = range(len(df_features))
PATID_list = df_features['PATID']
# get unique PATID and splite the based on PATID
unique_PATID_list = PATID_list.unique()
train_ratio = 0.7
validation_ratio = 0.1
test_ratio = 0.2

# First split to separate out the training set
train_pat, temp_set = train_test_split(unique_PATID_list, test_size=(1 - train_ratio), random_state=42)

# Second split to divide the temp_set into validation and test sets
val_test_ratio = test_ratio / (validation_ratio + test_ratio)
val_pat, test_pat = train_test_split(temp_set, test_size=val_test_ratio, random_state=42)

train_df = df_features[df_features['PATID'].isin(train_pat)]
val_df = df_features[df_features['PATID'].isin(val_pat)]
test_df = df_features[df_features['PATID'].isin(test_pat)]

next_status
0    26951
1    19846
2    18001
Name: count, dtype: int64

In [3]:
print('#patient in train: ', len(train_df['PATID'].unique()), '# encounter: ',len(train_df))
print('#patient in val: ', len(val_df['PATID'].unique()), '# encounter: ',len(val_df))
print('#patient in test: ', len(test_df['PATID'].unique()), '# encounter: ',len(test_df))

#patient in train:  1767 # encounter:  45176
#patient in val:  252 # encounter:  6742
#patient in test:  506 # encounter:  12880

In [4]:
import pandas as pd
index_df = pd.DataFrame(train_df.index, columns=["index"])
index_df.to_csv("train_indices.csv", index=False)

index_df = pd.DataFrame(val_df.index, columns=["index"])
index_df.to_csv("val_indices.csv", index=False)

index_df = pd.DataFrame(test_df.index, columns=["index"])
index_df.to_csv("test_indices.csv", index=False)

In [9]:
import pickle
import numpy as np
from sklearn.model_selection import train_test_split
import os
import pandas as pd
adrd_demo = pd.read_csv("adrd_demo.csv")
adrd_demo

,Unnamed: 0,ID,BIRTH_DATE,SEX,HISPANIC,RACE,SOURCE_masked,first_MCI_date,first_AD_date,Age,Conv_days,first_ENC_date,last_ENC_date,days_after_MCI
0,9,14Oct2022drugrepurposing00022115,1954-04-11,F,N,05,source_3,2020-03-04,NaN,65.0,NaN,2012-02-02,2022-01-06,673.0
1,14,14Oct2022drugrepurposing00022059,1957-08-14,F,N,05,source_9,2016-10-27,NaN,59.0,NaN,2012-03-14,2021-10-28,1827.0
2,15,14Oct2022drugrepurposing00022027,1945-12-20,F,Y,OT,source_11,2015-11-10,NaN,69.0,NaN,2012-02-29,2020-08-17,1742.0
3,16,14Oct2022drugrepurposing00022011,1962-09-01,F,N,02,source_1,2019-07-18,NaN,56.0,NaN,2012-03-09,2022-01-20,917.0
4,18,14Oct2022drugrepurposing00021995,1949-12-03,M,N,05,source_3,2017-01-12,NaN,67.0,NaN,2016-01-07,2022-01-10,1824.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10866,28632,14Oct2022drugrepurposing00030122,1924-06-24,M,Y,05,source_11,2016-11-22,2017-10-31,92.0,343.0,2012-01-03,2021-11-21,1825.0
10867,28637,14Oct2022drugrepurposing00030162,1942-02-09,M,N,05,source_11,2017-06-12,2019-10-01,75.0,841.0,2014-01-04,2021-03-07,1364.0
10868,28662,14Oct2022drugrepurposing00037778,1936-03-04,M,N,05,source_11,2014-11-01,2019-10-09,78.0,1803.0,2012-03-19,2019-11-01,1826.0
10869,28697,14Oct2022drugrepurposing00031602,1945-07-15,M,N,03,source_11,2014-03-27,2014-12-12,68.0,260.0,2012-01-11,2021-10-06,2750.0
10870,28721,14Oct2022drugrepurposing00031050,1955-03-11,M,Y,05,source_1,2017-07-12,2019-02-26,62.0,594.0,2016-04-11,2020-02-27,960.0

In [13]:
AD = len(adrd_demo[adrd_demo['first_AD_date'].notna()])
MCI_AD_ratio = AD/len(adrd_demo[adrd_demo['first_MCI_date'].notna()])
print(AD,MCI_AD_ratio)

1137 0.10459019409437954

In [18]:
df = adrd_demo[adrd_demo['first_AD_date'].notna()].copy()
df['first_MCI_date'] = pd.to_datetime(df['first_MCI_date'])
df['first_AD_date'] = pd.to_datetime(df['first_AD_date'])

# Calculate days from MCI to AD
df['MCI_to_AD_days'] = (df['first_AD_date'] - df['first_MCI_date']).dt.days

# Calculate average
average_days = df['MCI_to_AD_days'].mean()

In [19]:
average_days

898.4863676341249